In [17]:
import numpy as np

arr1 = np.array([[1,2,3,4],
                 [4,3,2,1]])

# Reshape arr1 to 4 rows and 2 columns
arr2 = np.reshape(arr1, (4, 2))
print(arr2)
arr3 = np.arange(0,100,2)
print("arr3 " ,arr3)


[[1 2]
 [3 4]
 [4 3]
 [2 1]]
arr3  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]


## Arrange Methods in Numpy Start -Stop -Next


In [10]:
num = np.arrange(0,3,10)

NameError: name 'np' is not defined

In [ ]:
arr

## ReShape


In [19]:
r =np.ones((5,5))
print(r)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
